### ISSUE TITLE
It doesn't work now so I've fixed and enhanced this addon

### ISSUE THREAD

**Issue by arbi316** [phanx-wow/GridStatusHealTrace#2]
Latest version for BfA doesn't work properly so I've fixed it

Also I tweaked some spells like Essence Font and some shaman spells

And I made codes that works Healing Tide Totem, it works perfectly.

[https://pastebin.com/h7HRwtij](url)

**Comment by Phanx** [comment]
Since you already have a GitHub account, can you just open a pull request with your changes?

**Comment by Phanx** [comment]
Nevermind, I see you already did that. Closing this issue, and I'll take a look at the PR now.
